# config/database.yml
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  primary:
    adapter: sqlite3
    database: db/development.sqlite3
  cable:
    adapter: sqlite3
    database: db/development.sqlite3
  queue:
    adapter: sqlite3
    database: db/development.sqlite3

test:
  primary:
    adapter: sqlite3
    database: db/test.sqlite3
  cable:
    adapter: sqlite3
    database: db/test.sqlite3
  queue:
    adapter: sqlite3
    database: db/test.sqlite3

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    adapter: postgresql
  cable:
    url: <%= ENV.fetch("CABLE_DATABASE_URL", ENV["DATABASE_URL"]) %>
    adapter: postgresql
  queue:
    url: <%= ENV.fetch("QUEUE_DATABASE_URL", ENV["DATABASE_URL"]) %>
    adapter: postgresql
