# config/database.yml

default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  # Rails will read the full connection string from the env var on Render.
  # The fallback keeps asset builds from crashing if DATABASE_URL isn't present locally.
  url: <%= ENV.fetch("DATABASE_URL", "postgres://user:pass@localhost:5432/dummy") %>
  adapter: postgresql
